---
  - hosts: master:worker:ingress:storage
    any_errors_fatal: true
    name: "{{ play_name | default('Configure Kubernetes CNI') }}"
    serial: "{{ serial_count | default('100%') }}"
    become: yes
    vars_files:
      - group_vars/all.yaml

    tasks:
      - name: create /opt/cni/bin directory
        file:
          path: "/opt/cni/bin"
          state: directory
      - name: download cni-bin image
        command: docker pull {{ images.cni_bin }}
      - name: install cni binaries
        command: docker run -e OVERWRITE=true -v /opt/cni/bin:/host/opt/cni/bin {{ images.cni_bin }}
