---
  - hosts: master[0]
    name: "{{ play_name | default('Configure Internal Docker Registry') }}"
    become: yes
    run_once: true

    roles:
      - role: docker-registry-container
        when: deploy_internal_docker_registry|bool == true and (upgrading is not defined or upgrading|bool == false) # setup a registry running on master[0]
